# permissions for end users to edit starburstaddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: starburstaddon-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: starburstaddon-operator
    app.kubernetes.io/part-of: starburstaddon-operator
    app.kubernetes.io/managed-by: kustomize
  name: starburstaddon-editor-role
rules:
- apiGroups:
  - managed-tenants.redhat.com
  resources:
  - starburstaddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-tenants.redhat.com
  resources:
  - starburstaddons/status
  verbs:
  - get
