apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: starburstaddon-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StarburstAddon is the Schema for the starburstaddons API
      displayName: Starburst Addon
      kind: StarburstAddon
      name: starburstaddons.managed-tenants.redhat.com
      version: v1alpha1
  description: Starburst Addon Operator
  displayName: starburstaddon-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - Kubernetes
  - OpenShift
  links:
  - name: Starburstaddon Operator
    url: https://starburstaddon-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
